sonar.projectKey=Zr0AM_dnd-app-sim
sonar.organization=zr0am
sonar.host.url=https://sonarcloud.io

# Multi-module aggregated JaCoCo coverage report from sim-service
sonar.coverage.jacoco.xmlReportPaths=sim-service/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml

# Character encoding
sonar.sourceEncoding=UTF-8
